# Generated by Django 5.1.7 on 2025-04-29 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrogRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'frog_app_frog_rarity',
            },
        ),
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/frog_images/')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frog_app.frograrity')),
            ],
        ),
        migrations.CreateModel(
            name='FrogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('frog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frog_app.frog')),
            ],
            options={
                'db_table': 'frog_app_frog_user',
            },
        ),
    ]
