# Generated by Django 5.1.7 on 2025-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frog',
            name='image',
            field=models.ImageField(null=True, upload_to='img/frog_images/'),
        ),
    ]
