# Generated by Django 5.1.7 on 2025-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog_app', '0003_alter_frog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='frograrity',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
    ]
