# Generated by Django 5.1.7 on 2025-05-12 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frog_app', '0004_frograrity_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='froguser',
            unique_together={('user', 'frog')},
        ),
    ]
