# Generated by Django 5.1.7 on 2025-05-12 07:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog_app', '0005_alter_froguser_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrogAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateField(default=datetime.date.today)),
                ('frog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frog_app.frog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'frog_app_frog_acquisition',
                'unique_together': {('user', 'frog')},
            },
        ),
    ]
