# Generated by Django 5.1.7 on 2025-05-12 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frog_app', '0006_frogacquisition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='frogacquisition',
            old_name='acquired_at',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='frogacquisition',
            unique_together={('user', 'date')},
        ),
    ]
